service: docenter-frontend

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: ${opt:stage}
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true
  exclude:
    - ./**

functions:
  docenter-frontend:
    name: ${self:service}-${self:provider.stage}
    handler: entrypoint.handler
    package:
      include:
        - entrypoint.js
        - next.config.js
        - pages/**
        - styles/**
        - public/**
        - build/_next/**
        - node_modules/**
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:provider.stage}}
      subnetIds: ${self:custom.subnets.${self:provider.stage}}
    environment:
      API_BASE_URL: ${ssm:/docenter-front-end/${self:provider.stage}/api-base-url}
      API_KEY: ${ssm:/docenter-front-end/${self:provider.stage}/api-key}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: "redirect-to-https"
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  domain-name:
    Fn::Join:
      - "."
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  aliases:
    staging: docenter-staging.hackney.gov.uk
  certificate-arn:
    staging: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
  securityGroups:
    staging:
      - sg-0166cbf56b7e77af0
  subnets:
    staging:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
